### ISSUE TITLE
cp: cannot stat './nlpcc_data/char/embed': No such file or directory

### ISSUE THREAD

**Issue by StevenLOL** [JerrikEph/nlpcc#1]
./quick_run.sh
...
...
cp:  cannot stat './nlpcc_data/char/embed': No such file or directory

**Comment by JerrikEph** [comment]
可以忽略，embed本身是一个symbolic链接，然而默认是没有使用预训的embedding的。如果要用预训好的embedding 的话可以按照all_data/embed 中的示例做一个embedding文件，里面应该有说明。

**Comment by StevenLOL** [comment]
OK, thanks.
